### ISSUE TITLE
Saved SVG file rendered wrongly in other apps

### ISSUE THREAD

**Issue by Symbian9** [mjhorvath/Video-Game-Keyboard-Diagrams#1]
While it looks good in browser, in other apps saved SVG is fully broken

### In Pale Moon (web browser)

- https://linux.palemoon.org

![pic.1](https://i.imgur.com/PyMojbd.png)

### In sK1 (vector editor)

- https://github.com/sk1project/sk1-wx

![pic.2](https://i.imgur.com/IQ5563Z.png) 

### In nomacs (image viewer)

- https://github.com/nomacs/nomacs

![pic.3](https://i.imgur.com/Wzxgtga.png)

### Details

- http://isometricland.net/keyboard/keyboard-diagram-kerbal-space-program-flight.svg?sty=15&lay=1&fmt=1&ten=1

![pic.4](https://i.imgur.com/383twp6.png)

**Comment by mjhorvath** [comment]
It looks fine in Inkscape. Not sure what to tell you. Let me know when you zero in on what the issue is.

**Comment by mjhorvath** [comment]
Okay, I think the issue is that there are nested SVG elements. But there is nothing wrong with this. You will have to switch to using a more advanced editor such as Inkscape.

**Comment by mjhorvath** [comment]
Okay I can think of a workaround, but I will have to consult with people at Stack Exchange first to determine if it's the "correct" thing to do.

**Comment by mjhorvath** [comment]
I made some changes. Can you test and see if things work better for you now?

**Comment by Symbian9** [comment]
> Can you test and see if things work better for you now?

OK.

### In Pale Moon (web browser)

Looks good!

![pic.1](https://i.imgur.com/9tDWWhU.png)

### In Inkscape (vector editor)

Looks good!

![pic.2](https://i.imgur.com/VWRHY0E.png)

### In sK1 (vector editor)

Now it looks much better.

The only issue — seems like all text lines in multi-line key label placed on same height (possibly, some `sK1` issue with SVG support; FYI @sk1project @maxim-s-barabash )

![pic.3](https://i.imgur.com/zJggiTA.png)

### In nomacs (image viewer)

Better, but not good (possibly, `nomacs` has itself some additional issues with SVG)

![pic.4](https://i.imgur.com/CYfhkvS.png)

**Comment by mjhorvath** [comment]
Okay, that's an improvement at least.
