### ISSUE TITLE
Can you please add Apple/Macintosh DE 110 Key (A1243) keyboard layout?

### ISSUE THREAD

**Issue by 7wells** [mjhorvath/Video-Game-Keyboard-Diagrams#13]
Hi Michael, your tool currently offers these layouts of Apple/Macintosh keyboards:
- UK 110 Key (A1048)
- US 109 Key (A1048)
- US 109 Key (A1243)

I own this Apple/Macintosh DE 110 Key (A1243) keyboard. Could you please consider adding this layout?
![1](https://user-images.githubusercontent.com/65889763/116266645-f816ec80-a77b-11eb-8ad9-5cce3bbb8a03.png)

Do you have a hint for me if/how I could use one of the existing layouts for the time being, without the need to later redo everything from scratch again? Again, thank you so much for your help! 😄

**Comment by 7wells** [comment]
PS:
If I can help you with this (hopefully, without a need for you to invest too much time for explaining it to me), I am happy doing so. Just let me know.

**Comment by mjhorvath** [comment]
I haven't made a tool to do this yet, so I will have to create it by hand. I would appreciate it if you could post a higher resolution photo and also list the model number. Thanks. I have finals in school the next two weeks so may be busy.

**Comment by 7wells** [comment]
If there is anything else, I could possibly help, please let me know. Hopefully, the photos are good enough. There are 2 flavours of F3 and F4 keys for this keyboard, but that should not matter.

For your school finals I wish you much success - especially in these difficult times! 👍

![1](https://user-images.githubusercontent.com/65889763/116666114-e19aac00-a99a-11eb-813d-c5301d89f34c.png)
![1](https://i.ebayimg.com/images/g/o10AAOSwGhpe~acN/s-l1600.png)

**Comment by 7wells** [comment]
PS: This is the Apple wired keyboard model A1243 with German (DE) 110 keys layout.

**Comment by mjhorvath** [comment]
What is the German word for the "Clear" key? (A box with an X inside of it on the numeric keypad.) Thanks!

**Comment by mjhorvath** [comment]
I created the German Mac keyboard. Please double check and make sure it is okay.

**Comment by 7wells** [comment]
Thanks a lot. I will do - and hope your finals were good! :)

**Comment by mjhorvath** [comment]
They were okay, thanks!

**Comment by 7wells** [comment]
@mjhorvath 
Also here: Thank you so much for adding the German Apple/Macintosh keyboard! You had some questions, of which I can help answering some.

- About the key with a box with an X inside of it on the numeric keypad
Since I am no Apple user (just have this keyboard for historic reasons), I do not know how that key is called. But when looking at non-Apple keyboards, there is a similar key there, which I believe is called "NumLock". You can use this key to switch between the pure numbers of those keys and arrows (up, down, left, right) or page up/down. If this is really also true for this Apple keyboard, I do not know for sure, though.

- You asked, what are the German names for the "Command" keys.
I assume you mean the 2 keys with "cmd" and a sign left and right of the space bar, and I would not change that to English but keep "cmd", as that is as it appears also on the German keyboard. If somebody speaking German wants to refer to these keys, I assume s/he would also say "command" keys.

- About these characters:
²: Right-alt + 2
³: Right-alt + 3
Interestingly, Right-alt + 4, 5, and 6 does not do anything.
{: Right-alt + 7
[: Right-alt + 8
]: Right-alt + 9
}: Right-alt + 0
\: Right-alt + ß (in German: "scharfes S")
~: Right-alt + +
|: Right-alt + <
µ: Right-alt + m
Despite the @ is shown in the "L" key, you have to press Right-alt + Q (not L), at least when using Windows 10, where I tested all this. The "E" key also shows the € sign, which is indeed shown when pressing Right-alt + E.

If you have more questions, please let me know. 👍
