### ISSUE TITLE
Could original key imprints be dimmed for better readability of new key mappings?

### ISSUE THREAD

**Issue by 7wells** [mjhorvath/Video-Game-Keyboard-Diagrams#14]
Hi Michael,

Could original key imprints be dimmed, so the applied key mappings are easier to read? See first row of an Apple/Macintosh keyboard with a few mappings applied as an example:
![1](https://user-images.githubusercontent.com/65889763/116370790-08c27380-a80b-11eb-9525-f4cb0a3d50e6.png)
The F7 key's original imprint reads "Track -" on top and "F7" at the bottom, which makes the new mappings ("Set 3" and "Jump 3") a bit difficult to read, similarly with F8 and other keys.

As an example for the **F7 key**, here are my (clumsy) attempts to blur (I didn't know how to dim)...
![2](https://user-images.githubusercontent.com/65889763/116372315-95216600-a80c-11eb-8971-0200b0437656.png)

... and to completely remove the original imprint:
![3](https://user-images.githubusercontent.com/65889763/116372327-981c5680-a80c-11eb-8f0e-7662b3252b31.png)

I don't know about other users' preferences. At least for me, when looking at a printed keyboard layout, it is not necessary to have all the original key imprints visible. If they could be dimmed (all keys or even user-selected ones), maybe this could be beneficial. What do you think about this?

**Comment by mjhorvath** [comment]
This is a good idea, thanks. I am not sure I will have time to do this in the near future, however.

**Comment by 7wells** [comment]
It's the lines below. When you set the value of '.txtxxx ' to the same as of the corresponding '.recxxxx', the imprinted key becomes invisible (might make more sense when only applying this to keys that have an assigned mapping, i.e. the unused keys could remain as they are - if I might suggest this).
```
.recred	{fill:#FC9C93;}	/* ( 74, 40, 30) */
.recyel	{fill:#CEB46C;}	/* ( 74, 40, 90) */
.recgrn	{fill:#7CC690;}	/* ( 74, 40,150) */
.reccyn	{fill:#0CC9D9;}	/* ( 74, 40,210) */
.recblu	{fill:#80B9FF;}	/* ( 74, 40,270) */
.recmag	{fill:#E4A0DB;}	/* ( 74, 40,330) */
.recwht	{fill:#ffffff;stroke:#c0c0c0;}
.recgry	{fill:#808080;}
.recblk	{fill:#404040;}
.recorg	{fill:#ECA777;}	/* ( 74, 40, 60) */
.recolv	{fill:#A8BF75;}	/* ( 74, 40,120) */
.recbrn	{fill:#685510;}	/* ( 37, 40, 90) */
.recnon	{fill:#B6B6B6;} /* ( 74,  0,  0) */
.txtred	{fill:#000000;}
.txtyel	{fill:#000000;}
.txtgrn	{fill:#000000;}
.txtcyn	{fill:#000000;}
.txtblu	{fill:#000000;}
.txtmag	{fill:#000000;}
.txtwht	{fill:#000000;}
.txtgry	{fill:#000000;}
.txtblk	{fill:#ffffff;}
.txtorg	{fill:#000000;}
.txtolv	{fill:#000000;}
.txtbrn	{fill:#ffffff;}
.txtnon	{fill:#000000;}
```

**Comment by 7wells** [comment]
@mjhorvath 
Hi Michael, this looks really great - thank you! I selected "Macintosh" (maybe you would like considering to rename this to "Apple"?), "CIELCh Plain (Light)" (BTW, what does "CIELCh" stand for?"), "Test Sample", and the other default values. Your additional "Key Labels" (dimmed, blurred, hidden) are very helpful! 😄 

PS: You had some questions about the German keyboard keys. I will reply there (https://github.com/mjhorvath/Video-Game-Keyboard-Diagrams/issues/13).
