### ISSUE TITLE
Add the ability to export/print from the Editor

### ISSUE THREAD

**Issue by CapoFantasma97** [mjhorvath/Video-Game-Keyboard-Diagrams#5]
The Editor is very interesting and easy to use.

It could be helpful if you could allow people to share their own keyboard layouts and keybinds, by adding an option to export the result without submitting as a game/program layout.

(also, side note, font size can be too small at times, would be helpful to allow to tweak that too in the Editor)

**Comment by mjhorvath** [comment]
Good idea. I have started working on this.

**Comment by mjhorvath** [comment]
I added an 'Export' button to the submission form so you can download the work-in-progress. I could add a 'Preview' button too if it is needed. But there are a lot of buttons already and I don't know if I can fit another one without pushing them further down the page.

**Comment by reeve567** [comment]
What browsers has export been tested to work on?  On both Chrome and Waterfox, the only thing that seems to get exported is the color titles (All I've tried so far is naming a key with capnor)

**Comment by mjhorvath** [comment]
Oops, I must have broken something! I will look into it.

**Comment by mjhorvath** [comment]
This should be fixed now.
