### ISSUE TITLE
Feature Request: Save Keyboard Layouts

### ISSUE THREAD

**Issue by DarthFutuza** [mjhorvath/Video-Game-Keyboard-Diagrams#8]
Hi, mjhorvath!  Just wanted to say thanks for making this project I've found it very useful.

It would be nice if there was a way for users to export/import saved key mappings in the future (I know they can submit complete ones, but this is for cases where its WIP etc or they aren't ready to be shared).  For example, either generating a unique url key that would allow a user to go back to a previously created key diagram and edit where they left off, or if you don't want to store data that way, then perhaps export it as a json file (or something similar) that would could be imported by the user later on?  

(As a background, I found the project useful for creating visual representations for users/other developers for games I develop and was hoping to be able to edit key bindings after initially creating them as the game changes/develops.  That said, having it exportable as html, is very nice and means I can probably dynamically generate new keyboards based on the game's actual keybindings in real time - though I haven't bothered to try doing that yet.)

**Comment by mjhorvath** [comment]
I can export/import JSON. Not sure when I'll find the time since it will require some work.

**Comment by mjhorvath** [comment]
You can now export/import JSON from the submission form. There's a curly braces { } icon in the top-right of the form. Click on the icon and you will see where you can get/set the JSON. Currently you cannot alter the layout however. Only the bindings.
